### ISSUE TITLE
https://github.com/lukewestby/elm-http-builder/zipball/6.0.0/ is no longer available

### ISSUE THREAD

**Issue by ewfarns** [rtfeldman/elm-0.19-workshop#26]
Hello.

 I'm watching the "introduction to Elm, V2." One of the resources used by the source files, "https://github.com/lukewestby/elm-http-builder/zipball/6.0.0/" is no longer available. I could change the elm.json file to reflect the newer version (7.0.0), but that may break other dependencies. Suggestions?

**Comment by 1Marc** [comment]
The releases are found here: https://github.com/lukewestby/elm-http-builder/releases/tag/6.0.0

**Comment by ewfarns** [comment]
Thank you. That sorts my issue. I'll change the link. Cheers.
